name: Build and Unit Tests

on:
  push:
    branches:
      - 'release'
      - 'main'
  pull_request:
    branches:
      - 'release'
      - 'main'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'
          registry-url: https://registry.npmjs.org/
      - run: yarn install --frozen-lockfile # optional, --immutable
      - run: yarn generate:collections
      - run: yarn test:ci
      - run: yarn build
